### ISSUE TITLE
Fix panic after restarting taker/maker with an open CFD

### ISSUE THREAD

**Issue by luckysori** [itchysats/10101#202]
With https://github.com/itchysats/10101/pull/196 we allow opening a CFD via the UI, actually interacting with the underlying Lightning node.

Unfortunately, restarting the "taker" or the maker runs into a panic. The theory is that this is caused by a serde bug introduced with https://github.com/lightningdevkit/rust-lightning/commit/dd206f1db786aa51dbacee41df98adbbdf423546.

Taker:
```
2022-11-15 11:47:24  INFO ten_ten_one::logger: Initialized logger
2022-11-15 11:47:24 DEBUG ten_ten_one::wallet: Wallet will be stored on disk data_dir="/home/luckysori/.local/share/com.example.with_flutter"
thread 'frb_workerpool' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidValue', rust/src/lightning.rs:332:68
```

Maker:
```
2022-11-15 11:47:35  INFO maker::logger: Initialized logger
2022-11-15 11:47:35 DEBUG ten_ten_one::wallet: Wallet will be stored on disk data_dir="/tmp"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidValue', rust/src/lightning.rs:332:68
```

**Comment by bonomat** [comment]
already fixed in our ldk fork
